version: '3.8'

services:
  backend:
    build:
      context: ./sintad-blog-backend
    container_name: sintad-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./sintad-blog-frontend
    container_name: sintad-frontend
    ports:
      - "4300:80"
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    container_name: sintad-db
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: sintad
      POSTGRES_PASSWORD: sintad
      POSTGRES_DB: dbSintadBlog
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge