version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - sintad-blog-network

  backend:
    build:
      context: ./sintad-blog-backend
    container_name: sintad-backend
    ports:
      - "8080:8080"
    networks:
      - sintad-blog-network
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  frontend:
    build:
      context: ./sintad-blog-frontend
    container_name: sintad-frontend
    ports:
      - "4300:80"
    networks:
      - sintad-blog-network
    depends_on:
      - backend

  postgres:
    container_name: sintad-db
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: sintad
      POSTGRES_PASSWORD: sintad
      POSTGRES_DB: dbSintadBlog
    ports:
      - "5432:5432"
    networks:
      - sintad-blog-network

networks:
  sintad-blog-network:
    name: sintad-blog-network
    driver: bridge